Show the exception detailed message when available
Ruby 3.2 introduced an `Exception#detailed_message` method to allow gems
such as `did_you_mean` and `error_highlight` to enrich the exception
message.  `Exception#detailed_message`, by default, shows the error
message, the exception class name, and optional highlighting using ANSI
escape sequences. Previously, those gems modified `Exception#message`,
which led to broken test suites.

The problem with this change is that, as we only show
`Exception#message`, we stopped showing valuable information, such as
typo corrections and error locations.

This commit reintroduces this feedback by using the
`Exception#detailed_message` whenever available.

After this change, exceptions with detailed messages will be shown as:

```
     NoMethodError:
       undefined method `upcsae' for an instance of String (NoMethodError)

           "meow".upcsae
                 ^^^^^^^
       Did you mean?  upcase
```

Co-authored-by: Phil Pirozhkov <pirj@users.noreply.github.com>